language: c
 
branches:
  only:
    - master

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq lua5.1 lua5.2 luajit

script:
  - lua5.1 test.lua
  - lua5.2 test.lua
  - luajit test.lua
